# Generated by Django 3.1.1 on 2020-10-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_auto_20201002_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_desc',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
