# Generated by Django 3.1.2 on 2020-10-05 19:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_post_short_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.DateTimeField(default=datetime.datetime(2020, 10, 5, 19, 31, 31, 367046, tzinfo=utc))),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('desc', models.TextField(max_length=250)),
                ('status', models.CharField(choices=[('writing', 'В процессе'), ('to_review', 'Требует проверки'), ('blocked', 'Заблокирована'), ('opened', 'Открыта')], default='writing', max_length=9)),
                ('publish', models.DateTimeField(default=datetime.datetime(2020, 10, 5, 19, 31, 31, 365715, tzinfo=utc))),
            ],
            options={
                'db_table': 'lectures',
                'ordering': ('publish',),
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='article',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='lectures.lecture'),
        ),
    ]
