# Generated by Django 3.1.2 on 2020-10-05 19:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_auto_20201005_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('writing', 'В процессе'), ('to_review', 'Требует проверки'), ('ready', 'Готова')], default='writing', max_length=9),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 19, 35, 34, 194413, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 19, 35, 34, 192966, tzinfo=utc)),
        ),
    ]
