# Generated by Django 3.1.2 on 2020-10-05 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_auto_20201005_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 19, 40, 47, 903662, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 5, 19, 40, 47, 902172, tzinfo=utc)),
        ),
    ]
