# Generated by Django 3.1.2 on 2020-10-06 18:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0006_auto_20201005_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 18, 38, 58, 190213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 18, 38, 58, 188768, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h2_title', models.CharField(max_length=100)),
                ('h2_slug', models.SlugField(max_length=120)),
                ('body', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='lectures.article')),
            ],
            options={
                'db_table': 'sections',
            },
        ),
    ]
