# Generated by Django 3.1.2 on 2020-10-06 19:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_auto_20201006_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('publish',)},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('publish',)},
        ),
        migrations.AddField(
            model_name='section',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 19, 3, 45, 135681, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 19, 3, 45, 134053, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 6, 19, 3, 45, 132591, tzinfo=utc)),
        ),
    ]
